name: GitHub Pages

on:
  push:
    tags: [ "v*.*" ]
  workflow_dispatch:


jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4

      - run: cp src/swydd/__init__.py docs/swydd.py

      - name: Upload artifact
        uses: actions/upload-pages-artifact@latest
        with:
          path: ./docs

  deploy:
    runs-on: ubuntu-latest
    needs: build

    permissions:
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}


    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@latest
