name: Run Tests

on:
  push:
    branches:
      - main
  workflow_dispatch:
  workflow_call:


jobs:
  tests:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v3

      - name: Set up Python
        run: uv python install

      - name: Install the project
        run: uv sync

      - name: run tests
        run: ./tasks.py tests

